default_config:
lovelace:
  mode: yaml
demo:

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: network_out
        arg: "wlp2s0"
      - type: load_1m
      - type: load_5m
      - type: load_15m
