resources:
  - url: http://127.0.0.1:5000/canvas-gauge-card.js?v6
    type: module
views:
  - title: Example
    cards:
      - type: "custom:canvas-gauge-card"
        name: Canvas Guage Card Development
        card_height: 125
        #background_color: "#000"
        entity: sensor.processor_use
        gauge:
          colorValueBoxBackground: "#000"
          borderShadowWidth: 0
          borderOuterWidth: 0
          borderMiddleWidth: 0
          borderInnerWidth: 0
          animationDuration: 1500
          animationRule: linear
          borders: false
          colorPlate: "#ddd"
          height: 210
          highlights:
            - color: "rgba(200, 50, 50, .75)"
              from: 80
              to: 100
          majorTicks:
            - "0"
            - "10"
            - "20"
            - "30"
            - "40"
            - "50"
            - "60"
            - "70"
            - "80"
            - "90"
            - "100"
          maxValue: 100
          minValue: 0
          minorTicks: 2
          needleCircleInner: false
          needleCircleOuter: true
          needleCircleSize: 7
          needleType: arrow
          needleWidth: 2
          startAngle: 90
          strokeTicks: true
          ticksAngle: 180
          type: radial-gauge
          valueBox: false
          width: 210
        style:
          left: 4.2%
          top: 9.6%
          transform: none
