
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

lovelace:
  mode: yaml
  resources:
  - url: /local/custom_cards/canvas-gauge-card.js
    type: module

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
     # - type: last_boot
     # - type: network_out
     #   arg: "wlp2s0"
      - type: load_1m
      #- type: load_5m
      #- type: load_15m

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
